In [2]:
import pandas as pd
ns_df = pd.read_csv('ns_202312.csv', index_col = 0, low_memory=False)
ns_df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,(브루스 커밍스의)한국현대사,브루스 커밍스 지음,창작과비평사,2001,9788936482190,NaN,0,NaN,911.07,2,50,2023-12-18,NaN
1,2,시지프 신화,알베르 카뮈 지음 ;김화영 옮김,민음사,2016,9788937463433,NaN,0,343,808,1,1,2023-12-17,NaN
2,3,TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소,하광용 지음,파람북,2023,9791192964683,NaN,0,2,001.3,1,1,2023-12-17,NaN
3,4,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,2017,9791188363520,NaN,0,1,907,1,0,2023-12-17,NaN
4,5,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,2023,9791192942513,NaN,0,2,907,1,0,2023-12-17,NaN

In [3]:
ns_book = ns_df.loc[:, '번호':'등록일자']
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,(브루스 커밍스의)한국현대사,브루스 커밍스 지음,창작과비평사,2001,9788936482190,NaN,0,NaN,911.07,2,50,2023-12-18
1,2,시지프 신화,알베르 카뮈 지음 ;김화영 옮김,민음사,2016,9788937463433,NaN,0,343,808,1,1,2023-12-17
2,3,TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소,하광용 지음,파람북,2023,9791192964683,NaN,0,2,001.3,1,1,2023-12-17
3,4,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,2017,9791188363520,NaN,0,1,907,1,0,2023-12-17
4,5,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,2023,9791192942513,NaN,0,2,907,1,0,2023-12-17

In [6]:
# boolean으로 제거

print(ns_df.columns)
# 원소별 비교
ns_df.columns != 'Unnamed: 13'
selected_columns = ns_df.columns != 'Unnamed: 13'
ns_book = ns_df.loc[:, selected_columns]
ns_book.head()

Index(['번호', '도서명', '저자', '출판사', '발행년도', 'ISBN', '세트 ISBN', '부가기호', '권',
       '주제분류번호', '도서권수', '대출건수', '등록일자', 'Unnamed: 13'],
      dtype='object')

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,(브루스 커밍스의)한국현대사,브루스 커밍스 지음,창작과비평사,2001,9788936482190,NaN,0,NaN,911.07,2,50,2023-12-18
1,2,시지프 신화,알베르 카뮈 지음 ;김화영 옮김,민음사,2016,9788937463433,NaN,0,343,808,1,1,2023-12-17
2,3,TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소,하광용 지음,파람북,2023,9791192964683,NaN,0,2,001.3,1,1,2023-12-17
3,4,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,2017,9791188363520,NaN,0,1,907,1,0,2023-12-17
4,5,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,2023,9791192942513,NaN,0,2,907,1,0,2023-12-17

In [11]:
# drop 메서드로 제거

ns_book = ns_df.drop(['부가기호', 'Unnamed: 13'], axis=1)
ns_book.drop('주제분류번호', axis=1, inplace=True) # 덮어쓰기
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,권,도서권수,대출건수,등록일자
0,1,(브루스 커밍스의)한국현대사,브루스 커밍스 지음,창작과비평사,2001,9788936482190,NaN,NaN,2,50,2023-12-18
1,2,시지프 신화,알베르 카뮈 지음 ;김화영 옮김,민음사,2016,9788937463433,NaN,343,1,1,2023-12-17
2,3,TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소,하광용 지음,파람북,2023,9791192964683,NaN,2,1,1,2023-12-17
3,4,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,2017,9791188363520,NaN,1,1,0,2023-12-17
4,5,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,2023,9791192942513,NaN,2,1,0,2023-12-17

In [13]:
# dropna() 메서드

# NaN이 하나 이상 포함된 행이나 열 삭제
ns_book = ns_df.dropna(axis=1)
ns_book.head()

   번호           ISBN  도서권수  대출건수        등록일자
0   1  9788936482190     2    50  2023-12-18
1   2  9788937463433     1     1  2023-12-17
2   3  9791192964683     1     1  2023-12-17
3   4  9791188363520     1     0  2023-12-17
4   5  9791192942513     1     0  2023-12-17

In [14]:
# 모든 값이 NaN인 열 삭제
ns_book = ns_df.dropna(axis=1, how='all')
ns_book.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,(브루스 커밍스의)한국현대사,브루스 커밍스 지음,창작과비평사,2001,9788936482190,NaN,0,NaN,911.07,2,50,2023-12-18
1,2,시지프 신화,알베르 카뮈 지음 ;김화영 옮김,민음사,2016,9788937463433,NaN,0,343,808,1,1,2023-12-17
2,3,TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소,하광용 지음,파람북,2023,9791192964683,NaN,0,2,001.3,1,1,2023-12-17
3,4,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,2017,9791188363520,NaN,0,1,907,1,0,2023-12-17
4,5,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,2023,9791192942513,NaN,0,2,907,1,0,2023-12-17

In [15]:
# 행 삭제하기

ns_book2 = ns_book.drop([0, 1])
ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
2,3,TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소,하광용 지음,파람북,2023,9791192964683,NaN,0,2,001.3,1,1,2023-12-17
3,4,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,2017,9791188363520,NaN,0,1,907,1,0,2023-12-17
4,5,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,2023,9791192942513,NaN,0,2,907,1,0,2023-12-17
5,6,세계 정치학 필독서 50:2500년 정치학 명저 50권을 한 권에,톰 버틀러 보던 지음;김문주 옮김,센시오,2023,9791166571329,NaN,0,NaN,340,1,1,2023-12-17
6,7,"팔레스타인, 100년 분쟁의 원인",정환빈 지음,인세50,2023,9791198542502,NaN,NaN,NaN,918.63,1,1,2023-12-17

In [16]:
ns_book2 = ns_book[2:]
ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
2,3,TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소,하광용 지음,파람북,2023,9791192964683,NaN,0,2,001.3,1,1,2023-12-17
3,4,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,2017,9791188363520,NaN,0,1,907,1,0,2023-12-17
4,5,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,2023,9791192942513,NaN,0,2,907,1,0,2023-12-17
5,6,세계 정치학 필독서 50:2500년 정치학 명저 50권을 한 권에,톰 버틀러 보던 지음;김문주 옮김,센시오,2023,9791166571329,NaN,0,NaN,340,1,1,2023-12-17
6,7,"팔레스타인, 100년 분쟁의 원인",정환빈 지음,인세50,2023,9791198542502,NaN,NaN,NaN,918.63,1,1,2023-12-17

In [17]:
# loc 메서드와 달리 파이썬 슬라이싱처럼 마지막 인덱스를 포함하지 않음

ns_book2 = ns_book[0:2]
ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,(브루스 커밍스의)한국현대사,브루스 커밍스 지음,창작과비평사,2001,9788936482190,NaN,0,NaN,911.07,2,50,2023-12-18
1,2,시지프 신화,알베르 카뮈 지음 ;김화영 옮김,민음사,2016,9788937463433,NaN,0,343,808,1,1,2023-12-17

In [18]:
selected_rows = ns_df['출판사'] == '한빛미디어'
ns_book2 = ns_book[selected_rows]

# loc 메서드로도 가능
# ns_book2 = ns_book.loc[selected_rows]

ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
446,447,사라진 개발자들,"캐시 클라이먼 지음, 이미령 외 옮김",한빛미디어,2023,9791169211291,NaN,NaN,NaN,004.099,1,0,2023-12-01
740,741,(혼자 해도 프로 작가처럼 잘 쓰는) 아이패드 캘리그래피 with 프로크리에이트,이용선 지음,한빛미디어,2023,9791169211024,NaN,NaN,NaN,005.56,1,1,2023-11-27
922,923,리팩터링 :코드 구조를 체계적으로 개선하여 효율적인 리팩터링 구현하기,"마틴 파울러 지음;개앞맵시,남기혁 옮김",한빛미디어,2020,9791162242742,NaN,9,NaN,005.14,1,2,2023-11-21
954,955,데이터 드리븐 리포트:상사와 고객을 설득하는 데이터 기반의 의사결정 with 파이썬,이상석 지음,한빛미디어,2023,9791169211574,NaN,9,NaN,005.76,1,3,2023-11-21
1313,1314,"앤서블로 시작하는 인프라 자동화 - 기초부터 실무까지, 플레이북 예제로 마스터하는 앤서블",장현정.이태훈.김병수 지음,한빛미디어,2023,9791169211499,NaN,NaN,NaN,005.1,1,2,2023-11-10

In [21]:
ns_book2 = ns_book[ns_book['대출건수'] > 1000]
ns_book2.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
132575,132576,"사피엔스 :유인원에서 사이보그까지, 인간 역사의 대담하고 위대한 질문",유발 하라리 지음 ;조현욱 옮김,김영사,2016,9788934972464,NaN,NaN,NaN,909,30,1799,2016-04-22
382514,382515,해커스 토익:Listening,David Cho 지음,해커스어학연구소,2005,9788990700148,NaN,1,NaN,740.77,29,1066,2005-02-01

In [23]:
# duplicated()로 중복된 행 확인

sum(ns_book.duplicated(subset=['도서명', '저자', 'ISBN']))

20571

In [24]:
dup_rows = ns_book.duplicated(subset=['도서명', '저자', 'ISBN'], keep=False) # 중복된 행을 모두 True로 표시한 불리언 배열을 반환
ns_book3 = ns_book[dup_rows]
ns_book3.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
1,2,시지프 신화,알베르 카뮈 지음 ;김화영 옮김,민음사,2016,9788937463433,NaN,0,343,808,1,1,2023-12-17
59,60,헤어질 결심=Decision to leave,박찬욱 감독,CJ 엔터테인먼트,2023,8809602683503,NaN,NaN,NaN,688.2,1,0,2023-12-13
197,198,코파닉스 119:Korean Phonics,이동훈 지음,이지북,2001,9788989422525,NaN,6,3,375.474,1,7,2023-12-06
238,239,멜랑콜리아 I-II,욘 포세 지음 ;손화수 옮김,민음사,2023,9788937464317,NaN,0,431,808,1,1,2023-12-01
243,244,멜랑콜리아 I-II,욘 포세 지음 ;손화수 옮김,민음사,2023,9788937464317,NaN,NaN,431,808,1,0,2023-12-01

In [25]:
# 같은 도서의 대출건수를 하나로 합치기

count_df = ns_book[['도서명', '저자', 'ISBN', '권', '대출건수']]
loan_count = count_df.groupby(by=['도서명', '저자', 'ISBN', '권'], dropna=False).sum() # NaN이 있는 행을 삭제하지 않습니다
loan_count.head()

                                                                                            대출건수
도서명                                             저자                       ISBN          권
 (꼭 필요한 것부터 쉽게 배우는) 자신만만 블로그 차근차근 배우기           김상현 지음                   9788955025637 NaN    38
 (대한민국이 한 번도 경험하지 못한) 가장 강력한 주식 시장이 온다          홍성학 지음                   9791188726806 NaN    11
 (맨처음 배우는) 세상의 직업                               엘레오노라 바르소티 글 ·그림 ;김태은 옮김 9788992924146 NaN    10
 (생초보도 쉽게 따라 할 수 있는 경매) 경매 교과서                  설마 안정일 지음                9788965023005 NaN    34
 (영잘원 리스닝과 패턴 영어의 절묘한 만남으로 태어난 ) 리스닝 ABC : 입문편  JD Kim 지음                9788993466089 NaN     5

In [26]:
dup_rows = ns_book.duplicated(subset=['도서명', '저자', 'ISBN', '권'])
unique_rows = ~dup_rows
ns_book3 = ns_book[unique_rows].copy()

In [27]:
sum(ns_book3.duplicated(subset=['도서명', '저자', 'ISBN', '권']))

0

In [28]:
ns_book3.set_index(['도서명', '저자', 'ISBN', '권'], inplace=True)
ns_book3.head()

                                                                            번호  \
도서명                                    저자                ISBN          권
(브루스 커밍스의)한국현대사                        브루스 커밍스 지음        9788936482190 NaN   1
시지프 신화                                 알베르 카뮈 지음 ;김화영 옮김 9788937463433 343   2
TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소  하광용 지음            9791192964683 2     3
역사의 연구:신축약판                            아놀드 토인비 지음;김진원 엮음 9791188363520 1     4
                                                         9791192942513 2     5

                                                                               출판사  \
도서명                                    저자                ISBN          권
(브루스 커밍스의)한국현대사                        브루스 커밍스 지음        9788936482190 NaN  창작과비평사
시지프 신화                                 알베르 카뮈 지음 ;김화영 옮김 9788937463433 343     민음사
TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소  하광용 지음            9791192964683 2       파람북
역사의 연구:신축약판                            아놀드 토인비 지음;김진원 엮음 9791188363520 1      바른북스
                                                         9791192942513 2      바른북스

                                                                            발행년도  \
도서명                                    저자                ISBN          권
(브루스 커밍스의)한국현대사                        브루스 커밍스 지음        9788936482190 NaN  2001
시지프 신화                                 알베르 카뮈 지음 ;김화영 옮김 9788937463433 343  2016
TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소  하광용 지음            9791192964683 2    2023
역사의 연구:신축약판                            아놀드 토인비 지음;김진원 엮음 9791188363520 1    2017
                                                         9791192942513 2    2023

                                                                            세트 ISBN  \
도서명                                    저자                ISBN          권
(브루스 커밍스의)한국현대사                        브루스 커밍스 지음        9788936482190 NaN      NaN
시지프 신화                                 알베르 카뮈 지음 ;김화영 옮김 9788937463433 343      NaN
TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소  하광용 지음            9791192964683 2        NaN
역사의 연구:신축약판                            아놀드 토인비 지음;김진원 엮음 9791188363520 1        NaN
                                                         9791192942513 2        NaN

                                                                           부가기호  \
도서명                                    저자                ISBN          권
(브루스 커밍스의)한국현대사                        브루스 커밍스 지음        9788936482190 NaN    0
시지프 신화                                 알베르 카뮈 지음 ;김화영 옮김 9788937463433 343    0
TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소  하광용 지음            9791192964683 2      0
역사의 연구:신축약판                            아놀드 토인비 지음;김진원 엮음 9791188363520 1      0
                                                         9791192942513 2      0

                                                                            주제분류번호  \
도서명                                    저자                ISBN          권
(브루스 커밍스의)한국현대사                        브루스 커밍스 지음        9788936482190 NaN  911.07
시지프 신화                                 알베르 카뮈 지음 ;김화영 옮김 9788937463433 343     808
TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소  하광용 지음            9791192964683 2     001.3
역사의 연구:신축약판                            아놀드 토인비 지음;김진원 엮음 9791188363520 1       907
                                                         9791192942513 2       907

                                                                            도서권수  \
도서명                                    저자                ISBN          권
(브루스 커밍스의)한국현대사                        브루스 커밍스 지음        9788936482190 NaN     2
시지프 신화                                 알베르 카뮈 지음 ;김화영 옮김 9788937463433 343     1
TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소  하광용 지음            9791192964683 2       1
역사의 연구:신축약판                            아놀드 토인비 지음;김진원 엮음 9791188363520 1       1
                                                         9791192942513 2       1

                                                                            대출건수  \
도서명                                    저자                ISBN          권
(브루스 커밍스의)한국현대사                        브루스 커밍스 지음        9788936482190 NaN    50
시지프 신화                                 알베르 카뮈 지음 ;김화영 옮김 9788937463433 343     1
TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소  하광용 지음            9791192964683 2       1
역사의 연구:신축약판                            아놀드 토인비 지음;김진원 엮음 9791188363520 1       0
                                                         9791192942513 2       0

                                                                                  등록일자
도서명                                    저자                ISBN          권
(브루스 커밍스의)한국현대사                        브루스 커밍스 지음        9788936482190 NaN  2023-12-18
시지프 신화                                 알베르 카뮈 지음 ;김화영 옮김 9788937463433 343  2023-12-17
TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소  하광용 지음            9791192964683 2    2023-12-17
역사의 연구:신축약판                            아놀드 토인비 지음;김진원 엮음 9791188363520 1    2023-12-17
                                                         9791192942513 2    2023-12-17

In [29]:
ns_book3.update(loan_count)
ns_book3.head()

                                                                            번호  \
도서명                                    저자                ISBN          권
(브루스 커밍스의)한국현대사                        브루스 커밍스 지음        9788936482190 NaN   1
시지프 신화                                 알베르 카뮈 지음 ;김화영 옮김 9788937463433 343   2
TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소  하광용 지음            9791192964683 2     3
역사의 연구:신축약판                            아놀드 토인비 지음;김진원 엮음 9791188363520 1     4
                                                         9791192942513 2     5

                                                                               출판사  \
도서명                                    저자                ISBN          권
(브루스 커밍스의)한국현대사                        브루스 커밍스 지음        9788936482190 NaN  창작과비평사
시지프 신화                                 알베르 카뮈 지음 ;김화영 옮김 9788937463433 343     민음사
TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소  하광용 지음            9791192964683 2       파람북
역사의 연구:신축약판                            아놀드 토인비 지음;김진원 엮음 9791188363520 1      바른북스
                                                         9791192942513 2      바른북스

                                                                            발행년도  \
도서명                                    저자                ISBN          권
(브루스 커밍스의)한국현대사                        브루스 커밍스 지음        9788936482190 NaN  2001
시지프 신화                                 알베르 카뮈 지음 ;김화영 옮김 9788937463433 343  2016
TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소  하광용 지음            9791192964683 2    2023
역사의 연구:신축약판                            아놀드 토인비 지음;김진원 엮음 9791188363520 1    2017
                                                         9791192942513 2    2023

                                                                            세트 ISBN  \
도서명                                    저자                ISBN          권
(브루스 커밍스의)한국현대사                        브루스 커밍스 지음        9788936482190 NaN      NaN
시지프 신화                                 알베르 카뮈 지음 ;김화영 옮김 9788937463433 343      NaN
TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소  하광용 지음            9791192964683 2        NaN
역사의 연구:신축약판                            아놀드 토인비 지음;김진원 엮음 9791188363520 1        NaN
                                                         9791192942513 2        NaN

                                                                           부가기호  \
도서명                                    저자                ISBN          권
(브루스 커밍스의)한국현대사                        브루스 커밍스 지음        9788936482190 NaN    0
시지프 신화                                 알베르 카뮈 지음 ;김화영 옮김 9788937463433 343    0
TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소  하광용 지음            9791192964683 2      0
역사의 연구:신축약판                            아놀드 토인비 지음;김진원 엮음 9791188363520 1      0
                                                         9791192942513 2      0

                                                                            주제분류번호  \
도서명                                    저자                ISBN          권
(브루스 커밍스의)한국현대사                        브루스 커밍스 지음        9788936482190 NaN  911.07
시지프 신화                                 알베르 카뮈 지음 ;김화영 옮김 9788937463433 343     808
TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소  하광용 지음            9791192964683 2     001.3
역사의 연구:신축약판                            아놀드 토인비 지음;김진원 엮음 9791188363520 1       907
                                                         9791192942513 2       907

                                                                            도서권수  \
도서명                                    저자                ISBN          권
(브루스 커밍스의)한국현대사                        브루스 커밍스 지음        9788936482190 NaN     2
시지프 신화                                 알베르 카뮈 지음 ;김화영 옮김 9788937463433 343     1
TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소  하광용 지음            9791192964683 2       1
역사의 연구:신축약판                            아놀드 토인비 지음;김진원 엮음 9791188363520 1       1
                                                         9791192942513 2       1

                                                                            대출건수  \
도서명                                    저자                ISBN          권
(브루스 커밍스의)한국현대사                        브루스 커밍스 지음        9788936482190 NaN  50.0
시지프 신화                                 알베르 카뮈 지음 ;김화영 옮김 9788937463433 343  48.0
TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소  하광용 지음            9791192964683 2     1.0
역사의 연구:신축약판                            아놀드 토인비 지음;김진원 엮음 9791188363520 1     0.0
                                                         9791192942513 2     0.0

                                                                                  등록일자
도서명                                    저자                ISBN          권
(브루스 커밍스의)한국현대사                        브루스 커밍스 지음        9788936482190 NaN  2023-12-18
시지프 신화                                 알베르 카뮈 지음 ;김화영 옮김 9788937463433 343  2023-12-17
TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소  하광용 지음            9791192964683 2    2023-12-17
역사의 연구:신축약판                            아놀드 토인비 지음;김진원 엮음 9791188363520 1    2023-12-17
                                                         9791192942513 2    2023-12-17

In [30]:
ns_book4 = ns_book3.reset_index()
ns_book4.head()

,도서명,저자,ISBN,권,번호,출판사,발행년도,세트 ISBN,부가기호,주제분류번호,도서권수,대출건수,등록일자
0,(브루스 커밍스의)한국현대사,브루스 커밍스 지음,9788936482190,NaN,1,창작과비평사,2001,NaN,0,911.07,2,50.0,2023-12-18
1,시지프 신화,알베르 카뮈 지음 ;김화영 옮김,9788937463433,343,2,민음사,2016,NaN,0,808,1,48.0,2023-12-17
2,TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소,하광용 지음,9791192964683,2,3,파람북,2023,NaN,0,001.3,1,1.0,2023-12-17
3,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,9791188363520,1,4,바른북스,2017,NaN,0,907,1,0.0,2023-12-17
4,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,9791192942513,2,5,바른북스,2023,NaN,0,907,1,0.0,2023-12-17

In [33]:
print(sum(ns_book['대출건수'] > 100), sum(ns_book4['대출건수'] > 100))

2544 2876

In [34]:
# columns가 바뀌었기 때문에 다시 세팅

ns_book4 = ns_book4[ns_book.columns]
ns_book4.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,(브루스 커밍스의)한국현대사,브루스 커밍스 지음,창작과비평사,2001,9788936482190,NaN,0,NaN,911.07,2,50.0,2023-12-18
1,2,시지프 신화,알베르 카뮈 지음 ;김화영 옮김,민음사,2016,9788937463433,NaN,0,343,808,1,48.0,2023-12-17
2,3,TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소,하광용 지음,파람북,2023,9791192964683,NaN,0,2,001.3,1,1.0,2023-12-17
3,4,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,2017,9791188363520,NaN,0,1,907,1,0.0,2023-12-17
4,5,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,2023,9791192942513,NaN,0,2,907,1,0.0,2023-12-17

In [35]:
ns_book4.to_csv('ns_book4.csv', index=False)

In [39]:
def data_cleaning(filename):
    """
    남산 도서관 장서 CSV 데이터 전처리 함수
    :param filenam: CSV 파일 이름
    """
    # 파일을 데이터 프레임으로 읽습니다.
    ns_df = pd.read_csv(filename, low_memory=False)
    # NaN인 열을 삭제합니다.
    ns_book = ns_df.dropna(axis=1, how='all')
    # 대출건수를 합치기 위해 필요한 행만 추출하여 count_df를 만듭니다
    count_df = ns_book[['도서명', '저자', 'ISBN', '권', '대출건수']]
    # 설정한 인덱스를 기준으로 대출건수를 groupby() 합니다.
    loan_count = count_df.groupby(by=['도서명', '저자', 'ISBN', '권'], dropna=False).sum()
    # 고유한 행만 추출하여 복사
    dup_rows = ns_book.duplicated(subset=['도서명', '저자', 'ISBN', '권'])
    unique_rows = ~dup_rows
    ns_book3 = ns_book[unique_rows].copy()
    # 인덱스 설정
    ns_book3.set_index(['도서명', '저자', 'ISBN', '권'], inplace=True)
    # loan_count의 대출건수를 업데이트
    ns_book3.update(loan_count)
    # 인덱스 재설정
    ns_book4 = ns_book3.reset_index()
    # 열 순서 변경
    ns_book4 = ns_book4[ns_book.columns]
    return ns_book4

In [43]:
new_ns_book4 = data_cleaning('ns_202312.csv')

In [7]:
import pandas as pd

data = [[1, 'a', 10], [2, 'b', 20], [3, 'a', 10]]
df = pd.DataFrame(data, columns = ['col1', 'col2', 'col3'])
df

   col1 col2  col3
0     1    a    10
1     2    b    20
2     3    a    10

In [16]:
df.groupby(['col1', 'col2']).sum()

           col3
col1 col2
1    a       10
2    b       20
3    a       10