In [1]:
import pandas as pd

ns_book4 = pd.read_csv('ns_book4.csv', low_memory=False)
ns_book4.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,(브루스 커밍스의)한국현대사,브루스 커밍스 지음,창작과비평사,2001,9788936482190,NaN,0,NaN,911.07,2,50.0,2023-12-18
1,2,시지프 신화,알베르 카뮈 지음 ;김화영 옮김,민음사,2016,9788937463433,NaN,0,343,808,1,48.0,2023-12-17
2,3,TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소,하광용 지음,파람북,2023,9791192964683,NaN,0,2,001.3,1,1.0,2023-12-17
3,4,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,2017,9791188363520,NaN,0,1,907,1,0.0,2023-12-17
4,5,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,2023,9791192942513,NaN,0,2,907,1,0.0,2023-12-17

In [4]:
ns_book4.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 419807 entries, 0 to 419806
Data columns (total 13 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   번호       419807 non-null  int64
 1   도서명      419407 non-null  object
 2   저자       419601 non-null  object
 3   출판사      414438 non-null  object
 4   발행년도     419771 non-null  object
 5   ISBN     419807 non-null  object
 6   세트 ISBN  25237 non-null   float64
 7   부가기호     322451 non-null  object
 8   권        67088 non-null   object
 9   주제분류번호   403519 non-null  object
 10  도서권수     419807 non-null  int64
 11  대출건수     419807 non-null  float64
 12  등록일자     419807 non-null  object
dtypes: float64(2), int64(2), object(9)
memory usage: 278.4 MB

In [5]:
ns_book4.isna().sum()

번호              0
도서명           400
저자            206
출판사          5369
발행년도           36
ISBN            0
세트 ISBN    394570
부가기호        97356
권          352719
주제분류번호      16288
도서권수            0
대출건수            0
등록일자            0
dtype: int64

In [9]:
import numpy as np

ns_book4.loc[0, '부가기호'] = np.nan
ns_book4.head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,(브루스 커밍스의)한국현대사,브루스 커밍스 지음,창작과비평사,2001,9788936482190,NaN,NaN,NaN,911.07,2,50.0,2023-12-18
1,2,시지프 신화,알베르 카뮈 지음 ;김화영 옮김,민음사,2016,9788937463433,NaN,0,343,808,1,48.0,2023-12-17

In [10]:
set_isbn_na_rows = ns_book4['세트 ISBN'].isna()

ns_book4.loc[set_isbn_na_rows, '세트 ISBN'] = ''
ns_book4['세트 ISBN'].isna().sum()

0

In [11]:
# fillna() 메서드

ns_book4.fillna('없음').isna().sum()

번호         0
도서명        0
저자         0
출판사        0
발행년도       0
ISBN       0
세트 ISBN    0
부가기호       0
권          0
주제분류번호     0
도서권수       0
대출건수       0
등록일자       0
dtype: int64

In [14]:
ns_book4['부가기호'].fillna('없음').isna().sum()
# 개수만 있는 판다스 시리즈 객체 반환

0

In [15]:
# 바꾸면서 전체 데이터프레임 반환

ns_book4.fillna({'부가기호':'없음'}).isna().sum()

번호              0
도서명           400
저자            206
출판사          5369
발행년도           36
ISBN            0
세트 ISBN         0
부가기호            0
권          352719
주제분류번호      16288
도서권수            0
대출건수            0
등록일자            0
dtype: int64

In [16]:
# replace() 메서드
# 1. 바꾸려는 값이 하나일 때 : replace(원래 값, 새로운 값)

ns_book4.replace(np.nan, '없음').isna().sum()

번호         0
도서명        0
저자         0
출판사        0
발행년도       0
ISBN       0
세트 ISBN    0
부가기호       0
권          0
주제분류번호     0
도서권수       0
대출건수       0
등록일자       0
dtype: int64

In [20]:
# 2. 바꾸려는 값이 여러개 일 때 : replace([원래 값 1, 원래 값2], [새로운 값 1, 새로운 값2])

ns_book4.replace([np.nan, '2001'], ['없음', '01']).head(2)
# ns_book4.replace({np.nan:'없음', '2001':'01'}).head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,(브루스 커밍스의)한국현대사,브루스 커밍스 지음,창작과비평사,01,9788936482190,,없음,없음,911.07,2,50.0,2023-12-18
1,2,시지프 신화,알베르 카뮈 지음 ;김화영 옮김,민음사,2016,9788937463433,,0,343,808,1,48.0,2023-12-17

In [21]:
# 3. 열 마다 다른 값으로 바꿀 때 : replace({열 이름: 원래 값}, 새로운 값)

ns_book4.replace({'부가기호': np.nan}, '없음').head(2)
# ns_book4.replace({'부가기호': {np.nan:'없음'}, '발행년도':{'2001', '01'}}).head(2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,(브루스 커밍스의)한국현대사,브루스 커밍스 지음,창작과비평사,2001,9788936482190,,없음,NaN,911.07,2,50.0,2023-12-18
1,2,시지프 신화,알베르 카뮈 지음 ;김화영 옮김,민음사,2016,9788937463433,,0,343,808,1,48.0,2023-12-17

In [22]:
# 정규 표현식

ns_book4.replace({'발행년도': {r'\d\d(\d\d)':r'\1'}}, regex=True).head()
# {r'\d{2}(\d{2})'}

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,(브루스 커밍스의)한국현대사,브루스 커밍스 지음,창작과비평사,01,9788936482190,,NaN,NaN,911.07,2,50.0,2023-12-18
1,2,시지프 신화,알베르 카뮈 지음 ;김화영 옮김,민음사,16,9788937463433,,0,343,808,1,48.0,2023-12-17
2,3,TAKEOUT 유럽역사문명:지식 바리스타 하광용의 인문학 에스프레소,하광용 지음,파람북,23,9791192964683,,0,2,001.3,1,1.0,2023-12-17
3,4,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,17,9791188363520,,0,1,907,1,0.0,2023-12-17
4,5,역사의 연구:신축약판,아놀드 토인비 지음;김진원 엮음,바른북스,23,9791192942513,,0,2,907,1,0.0,2023-12-17

In [25]:
# 문자열

ns_book4.replace({'저자': {r'(.*)\s\(지은이\)(.*)\s\(옮긴이\)': r'\1\2'},
                '발행년도': {r'\d\d(\d\d)':r'\1'}}, regex=True)[30:37]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
30,31,나와 타인을 번역한다는 것,"줌파 라히리,이승민",마음산책,23,9788960908512,,NaN,NaN,844,1,0.0,2023-12-16
31,32,한 권으로 끝내는 스마트폰 제품사진,채수창 지음,앤써북,23,9791198189240,,NaN,NaN,662.48,1,1.0,2023-12-16
32,33,아웃퍼포머의 힘,송의달 (지은이),W미디어,23,9791189172480,,NaN,NaN,070.4,1,1.0,2023-12-16
33,34,"전시디자인, 미술의 발견",김용주 (지은이),소동,23,9791193193020,,NaN,NaN,606.3,1,1.0,2023-12-16
34,35,오름 오름 101 트레킹 맵,박선정 (지은이),미니멈,23,9791187694267,,NaN,NaN,981.19902,1,0.0,2023-12-16
35,36,"인류세, 엑소더스","가이아 빈스,김명주",곰출판,23,9791189327255,,NaN,NaN,472.52,1,1.0,2023-12-16
36,37,"덜미, 사건플러스",한국일보 사회부 (지은이),북콤마,23,9791187572459,,NaN,NaN,364.45,1,1.0,2023-12-16

In [30]:
ns_book4.astype({'발행년도':'int32'})

ValueError: invalid literal for int() with base 10: '2022(2023 개정2쇄)'

In [27]:
ns_book4['발행년도'].str.contains('1988').sum()

453

In [32]:
invalid_number = ns_book4['발행년도'].str.contains('\D', na=True)
print(invalid_number.sum())
ns_book4[invalid_number].head(5)

859

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
638,642,미움받을 용기:사랑과 진정한 자립에 대한 아들러의 가르침,"기시미 이치로,고가 후미타케 [공]지음;전경아 옮김",인플루엔셜(주),2022(2023 개정2쇄),9791168340787,,NaN,2,189,1,7.0,2023-11-27
640,644,미움받을 용기 :자유롭고 행복한 삶을 위한 아들러의 가르침,"기시미 이치로,고가 후미타케 지음;전경아 옮김",인플루엔셜(주),2022(2023 개정2쇄),9791168340770,,NaN,1,189,1,7.0,2023-11-27
1008,1029,(사료) 고종시대사,"기획·편집: 김현영,나애자,이헌주,문일웅,전미희,권구훈,류준범,하명준,박진희 ;국사...",국사편찬위원회,2015-2022,9788982368158,9788982366635.0,9,NaN,911.059,1,0.0,2023-11-13
1139,1160,(影印) 韓國古典叢刊 .傳記類 7,?한국고전번역원?,韓國古典飜譯院,2021-2022,9788928409945,9788928406104.0,NaN,NaN,NaN,1,0.0,2023-11-13
4225,4336,벤야민 & 아도르노 =Walter Benjamin ＆ Theodor W. Adorn...,신혜경 지음,김영사,2009(2021 쇄),9788934931843,,0,30,990,1,2.0,2023-08-02

In [33]:
ns_book5 = ns_book4.replace({'발행년도':'.*(\d{4}).*'}, r'\1', regex=True)
ns_book5[invalid_number].head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
638,642,미움받을 용기:사랑과 진정한 자립에 대한 아들러의 가르침,"기시미 이치로,고가 후미타케 [공]지음;전경아 옮김",인플루엔셜(주),2023,9791168340787,,NaN,2,189,1,7.0,2023-11-27
640,644,미움받을 용기 :자유롭고 행복한 삶을 위한 아들러의 가르침,"기시미 이치로,고가 후미타케 지음;전경아 옮김",인플루엔셜(주),2023,9791168340770,,NaN,1,189,1,7.0,2023-11-27
1008,1029,(사료) 고종시대사,"기획·편집: 김현영,나애자,이헌주,문일웅,전미희,권구훈,류준범,하명준,박진희 ;국사...",국사편찬위원회,2022,9788982368158,9788982366635.0,9,NaN,911.059,1,0.0,2023-11-13
1139,1160,(影印) 韓國古典叢刊 .傳記類 7,?한국고전번역원?,韓國古典飜譯院,2022,9788928409945,9788928406104.0,NaN,NaN,NaN,1,0.0,2023-11-13
4225,4336,벤야민 & 아도르노 =Walter Benjamin ＆ Theodor W. Adorn...,신혜경 지음,김영사,2021,9788934931843,,0,30,990,1,2.0,2023-08-02

In [34]:
unknown_year = ns_book5['발행년도'].str.contains('\D', na=True)
print(unknown_year.sum())
ns_book5[unknown_year].head()

91

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
6021,6373,"안락사, 죽음과 그 밖의 것들","아드리아노 페시나 지음, 박은호 옮김",가톨릭대학교출판부,NaN,9788971083611,,NaN,NaN,NaN,1,4.0,2023-06-16
6098,6451,너무나도 소중하지만 하찮게 느껴지는 (자료실요청),이원종 지음,세상의 아침,NaN,9788992713146,,NaN,NaN,NaN,1,1.0,2023-06-16
13846,14565,서울특별시교육청남산도서관 공간 개선 연구,서울특별시교육청남산도서관,서울특별시교육청남산도서관,NaN,9791196873851,,NaN,NaN,022.3163,1,1.0,2022-11-14
24457,25836,아이와 함께 호캉스,김수정.김승남 지음,길벗,NaN,9791165218706,,NaN,NaN,981.102,1,8.0,2022-03-11
24458,25837,넷이 있었다,이시우 지음,황금가지,NaN,9791170520740,,NaN,NaN,813.7,1,7.0,2022-03-11

In [35]:
ns_book5.loc[unknown_year, '발행년도'] = '-1'
ns_book5 = ns_book5.astype({'발행년도': 'int32'})
ns_book5['발행년도'].gt(4000).sum()

131

In [37]:
dangun_yy_rows = ns_book5['발행년도'].gt(4000)
ns_book5.loc[dangun_yy_rows, '발행년도'] = ns_book5.loc[dangun_yy_rows, '발행년도'] - 2333
dangun_year = ns_book5['발행년도'].gt(4000)
print(dangun_year.sum())
ns_book5[dangun_year].head(2)

14

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
4389,4503,부자 아빠의 투자 가이드,"로버트 기요사키 지음, 박슬라 옮김",창비교육,5667,9791165702069,,NaN,NaN,NaN,1,7.0,2023-08-02
258566,271590,Modern art,[computer file],GROLIER,7611,9780717233243,,NaN,NaN,609.205,1,1.0,2009-05-07

In [38]:
ns_book5.loc[dangun_year, '발행년도'] = -1
old_books = ns_book5['발행년도'].gt(0) & ns_book5['발행년도'].lt(1900)
ns_book5[old_books]

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
5308,5466,"Braiding sweetgrass:indigenous wisdom, scienti...",Robin Wall Kimmerer,Penguin Books Ltd,220,9780141991979,,9,NaN,NaN,1,0.0,2023-07-10
14145,14865,역사에 별빛처럼 빛난 자들,강부원 지음,믹스커피,1101,9791170433538,,NaN,NaN,911.06,1,6.0,2022-11-04
14146,14866,여행인문지리학잡론,민양지 지음,시대의창,1028,9788959407934,,NaN,NaN,980.24,1,12.0,2022-11-04
14147,14867,우물 밖의 개구리가 보는 한국사,"마크 피터슨.신채용 지음, 홍석윤 옮김",지식의숲(넥서스),1105,9791166834257,,NaN,NaN,911,1,7.0,2022-11-04
14148,14868,서핑하는 정신,한은형 지음,작가정신,1107,9791160262964,,NaN,NaN,813.7,1,7.0,2022-11-04
22878,24110,대한민국 꽃 여행 가이드,황정희 지음,중앙books(중앙북스),405,9788927812890,,NaN,NaN,981.102,1,7.0,2022-04-07
22879,24111,처음 떠나는 산티아고 순례길 가이드북,조대현 지음,해시태그(Hashtag),327,9791191403770,,NaN,NaN,982.702,1,18.0,2022-04-07
22880,24112,롤랑의 노래,김준한 옮김,휴머니스트,411,9791160808261,,NaN,NaN,860,1,3.0,2022-04-07
22881,24113,이만하면 달콤한 인생입니다,고영주 지음,보다북스,405,9791197567933,,NaN,NaN,816.7,1,2.0,2022-04-07
22882,24114,헤어진 이들은 홍콩에서 다시 만난다,주성철 지음,김영사,328,9788934961895,,NaN,NaN,816.7,1,7.0,2022-04-07
22883,24115,나의 먹이,들개이빨 지음,콜라주,324,9788954685559,,NaN,NaN,818,1,9.0,2022-04-07
22884,24116,"두려움 없이, 당신 자신이 되세요","아니타 무르자니 지음, 황근하 옮김",샨티,331,9791188244874,,NaN,NaN,189,1,9.0,2022-04-07
22885,24117,손에 땀을 쥐게 하는 이야기 쓰는 법,"조단 E. 로젠펠드 지음, 정미화 옮김",아날로그(글담),407,9791187147923,,NaN,NaN,802,1,6.0,2022-04-07
22886,24119,소설 보다 : 봄 2022,김병운.위수정.이주혜 지음,문학과지성사,329,9788932039855,,NaN,NaN,813.708,1,5.0,2022-04-07
22887,24120,유령의 마음으로,임선우 지음,민음사,325,9788937442698,,NaN,NaN,813.7,1,22.0,2022-04-07
22888,24122,우리 집 식물 수업,정재경 지음,교보문고(단행본),325,9791159095955,,NaN,NaN,525,1,3.0,2022-04-07
22889,24123,공간 디자인의 기술,"가와카미 유키 지음, 이예린 옮김",리스컴,323,9791156162599,,NaN,NaN,595.4,1,7.0,2022-04-07
22890,24124,방구석 가드닝,"앤절라 S. 저드 지음, 서지희 옮김",문학수첩,325,9788983928979,,NaN,NaN,525,1,4.0,2022-04-07
22891,24125,8초 만에 통증 리셋,문교훈(문쌤) 지음,다산라이프,321,9791130689029,,NaN,NaN,512.44,1,10.0,2022-04-07
22892,24126,15분이면 뚝딱! 와인 안주 요리,최주리 지음,설렘(슬로디미디어),401,9791167850652,,NaN,NaN,594.563,1,7.0,2022-04-07
22893,24127,오거나이즈 타임,박정선 지음,북스고,328,9791167600240,,NaN,NaN,595.4,1,9.0,2022-04-07
22894,24128,코로나19 세계 대전,"산제이 굽타 지음, 박은영 옮김, 이재갑 감수",타인의사유,404,9791168941151,,NaN,NaN,513.97,1,9.0,2022-04-07
22895,24129,청소년 진로 수업 대본,권태용 등,마인드빌딩,408,9791190015776,,NaN,NaN,372.68,1,5.0,2022-04-07
22896,24130,타인의 신발을 신어보다,"브래디 미카코 지음, 정수윤 옮김",은행나무,318,9791167371393,,NaN,NaN,181.71,1,6.0,2022-04-07
22897,24131,"나는, 휴먼","주디스 휴먼.크리스틴 조이너 지음, 김채원.문영민 옮김",사계절,318,9791160949117,,NaN,NaN,338.3,1,7.0,2022-04-07
22898,24132,"책 읽는 인간, 호모 부커스",조상연 지음,파지트,404,9791197631689,,NaN,NaN,029,1,5.0,2022-04-07
22899,24133,몰입의 완성,"캐리 오버브루너 지음, 이소영 옮김",현대지성,225,9791139702637,,NaN,NaN,325.211,1,11.0,2022-04-07
22900,24134,비욘드 핸디캡,김종욱 외 지음,스리체어스,405,9791191652543,,NaN,NaN,338.3,1,1.0,2022-04-07
22901,24135,세계를 바꾼 명문장 : 경제학 1 보이지 않는 손 vs 야성적 충동,서정희 지음,매일경제신문사,405,9791164843893,,NaN,NaN,320,1,5.0,2022-04-07
22902,24136,철학자의 사랑법,김동규 지음,사월의책,401,9791192092010,,NaN,NaN,102,1,3.0,2022-04-07
22903,24137,모든 사람에게 사랑받을 필요는 없다,이평 지음,스튜디오오드리,321,9791191043679,,NaN,NaN,189.2,1,19.0,2022-04-07
96795,101953,"고흐 씨, 시 읽어 줄까요 :내 마음을 알아주는 시와 그림의 만남",이운진 지음,사계절,176,9788958284277,,0,NaN,811.7,1,6.0,2017-10-27
106214,112163,정신 병리학의 문제들,지은이: 지그문트 프로이트 ;옮긴이: 황보석,열린책들,151,9788932905181,,9,10,185.5,1,5.0,2017-04-26
115210,121976,(최근 7년간) 중요 민법판례 :[2009년 1월~2016년 6월 중요 판례],이광섭 편저,법학사,163,9788962898651,,9,NaN,365,1,14.0,2016-09-27
183599,195438,(한·중·일) 밥상 문화 :대표음식으로 본 3국 문화비교,김경은 지음,이가서,132,9788958643012,,0,NaN,381.75,1,32.0,2013-02-19
230285,242933,책으로 뒤덮인 집의 비밀,N.E. 보드 지음 ;피터 퍼거슨 그림 ;김지현 옮김,개암나무,1015,9788992844413,,7,NaN,843,1,15.0,2010-08-18
322842,336442,(밝혀질)우리歷史,吳在城 著,黎民族史硏究會,1607,9788986892130,,0,NaN,911,1,7.0,2006-07-06

In [39]:
ns_book5.loc[old_books, '발행년도'] = -1
ns_book5['발행년도'].eq(-1).sum()

142

In [40]:
import requests
from bs4 import BeautifulSoup

def get_book_title(isbn):
    url = 'https://www.yes24.com/Product/Search?domain=BOOK&query={}'
    r = requests.get(url.format(isbn))
    soup = BeautifulSoup(r.text, 'html.parser')
    title = soup.find('a', attrs={'class':'gd_name'}).get_text()
    return title

In [41]:
get_book_title(9788936482190)

'브루스 커밍스의 한국현대사'

In [44]:
na_rows = ns_book5['도서명'].isna() | ns_book5['저자'].isna() | \
          ns_book5['출판사'].isna() | ns_book5['발행년도'].isna().eq(-1)
print(na_rows.sum())
ns_book5[na_rows].head(2)

5943

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
129,130,수면의 과학,미셸 공드리 감독,NaN,2023,9788809848788,,NaN,NaN,688.2,1,0.0,2023-12-13
196,197,무엇이 사이비 신앙인가,김진홍 저,NaN,2002,9788917907506,,0,NaN,235.2,1,0.0,2023-12-06

In [49]:
import re

def get_book_info(row):
    title = row['도서명']
    author = row['저자']
    pub = row['출판사']
    year = row['발행년도']
    url = 'https://www.yes24.com/Product/Search?domain=BOOK&query={}'
    r = requests.get(url.format(row['ISBN']))
    soup = BeautifulSoup(r.text, 'html.parser')
    try:
        if pd.isna(title):
            title = soup.find('a', attrs={'class':'gd_name'}).get_text()       
    except AttributeError:
        pass
    try:
        if pd.isna(author):
            authors = soup.find('span', attrs={'class':'info_auth'}).findall('a')
            author_list = [auth.get_text() for auth in authors]
            author = ','.join(author_list)
    except AttributeError:
        pass
    try:
        if pd.isna(pub):
            pub = soup.find('span', attrs={'class':'info_pub'}).get_text()
    except AttributeError:
        pass
    try:
        if year == -1:
            year_str = soup.find('span', attrs={'class':'info_date'}).get_text()
            year = re.findall(r'\d{4}', year_str)[0]
    except AttributeError:
        pass
    
    return title, author, pub, year

In [50]:
updated_sample = ns_book5[na_rows].head(2).apply(get_book_info, axis=1, result_type='expand')
updated_sample

                0          1   2     3
129        수면의 과학  미셸 공드리 감독 NaN  2023
196  무엇이 사이비 신앙인가      김진홍 저 NaN  2002

In [8]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import re

def get_book_info(row):
    title = row['도서명']
    author = row['저자']
    pub = row['출판사']
    year = row['발행년도']
    url = 'https://www.yes24.com/Product/Search?domain=BOOK&query={}'
    r = requests.get(url.format(row['ISBN']))
    soup = BeautifulSoup(r.text, 'html.parser')
    try:
        if pd.isna(title):
            title = soup.find('a', attrs={'class':'gd_name'}).get_text()       
    except AttributeError:
        pass
    try:
        if pd.isna(author):
            authors = soup.find('span', attrs={'class':'info_auth'}).findall('a')
            author_list = [auth.get_text() for auth in authors]
            author = ','.join(author_list)
    except AttributeError:
        pass
    try:
        if pd.isna(pub):
            pub = soup.find('span', attrs={'class':'info_pub'}).get_text()
    except AttributeError:
        pass
    try:
        if year == -1:
            year_str = soup.find('span', attrs={'class':'info_date'}).get_text()
            year = re.findall(r'\d{4}', year_str)[0]
    except AttributeError:
        pass
    
    return title, author, pub, year

def data_fixing(ns_book4):
    """
    잘못된 값을 수정하거나 NaN을 채우는 함수
    :param ns_book4: data_cleaning() 함수에서 전처리된 데이터프레임
    """
    # 도서권수와 대출건수를 int32로 바꿉니다.
    ns_book4 = ns_book4.astype({'도서권수':'int32', '대출건수':'int32'})
    # NaN인 세트 ISBN을 빈 문자열로 바꿉니다.
    set_isbn_na_rows = ns_book4['세트 ISBN'].isna()
    ns_book4.loc[set_isbn_na_rows, '세트 ISBN'] = ''
    # 발행년도 열에서 연도 네 자리를 추출하여 대체합니다. 나머지 발행년도는 01로 바꿉니다.
    ns_book5 = ns_book4.replace({'발행년도':'.*(\d{4}).*'}, r'\1', regex=True)
    unknown_year = ns_book5['발행년도'].str.contains('\D', na=True)
    ns_book5.loc[unknown_year, '발행년도'] = '-1'
    # 발행년도를 int32로 바꿉니다.
    ns_book5 = ns_book5.astype({'발행년도': 'int32'})
    # 4000년 이상인 경우 2333년을 뺍니다.
    dangun_yy_rows = ns_book5['발행년도'].gt(4000)
    ns_book5.loc[dangun_yy_rows, '발행년도'] = ns_book5.loc[dangun_yy_rows, '발행년도'] - 2333
    # 여전히 4000년 이상인 경우 -1로 바꿉니다.
    dangun_year = ns_book5['발행년도'].gt(4000)
    ns_book5.loc[dangun_year, '발행년도'] = -1
    # 0~1900년 사이의 발행년도는 -1로 바꿉니다.
    old_books = ns_book5['발행년도'].gt(0) & ns_book5['발행년도'].lt(1900)
    ns_book5.loc[old_books, '발행년도'] = -1
    # 도서명, 저자, 출판사가 NaN이거나 발행년도가 -1인 행을 찾습니다.
    na_rows = ns_book5['도서명'].isna() | ns_book5['저자'].isna() | \
          ns_book5['출판사'].isna() | ns_book5['발행년도'].isna().eq(-1)
    # yes24 도서 상세 페이지에서 누락된 정보를 채웁니다.
    updated_sample = ns_book5[na_rows].apply(get_book_info, axis=1, result_type='expand')
    # 도서명, 저자, 출판사가 NaN이거나 발행년도가 -1인 행을 삭제합니다.
    ns_book6 = ns_book5.dropna(subset['도서명', '저자', '출판사'])
    ns_book6 = ns_book6[ns_book6['발행년도'] != -1]
    
    return ns_book6

In [9]:
ns_book4 = pd.read_csv('ns_book4.csv', low_memory=False)
ns_book6 = data_fixing(ns_book4)

TypeError: 'NoneType' object is not callable